"""add address table

Revision ID: 219a99174e61
Revises: c9c0373de061
Create Date: 2026-10-07 00:08:26.573979

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "219a99174e61"
down_revision: Union[str, Sequence[str], None] = "c9c0373de061"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "addresses",
        sa.Column("user_id", sa.String(length=26), nullable=False),
        sa.Column("recipient_name", sa.String(length=30), nullable=False),
        sa.Column("phone_number", sa.String(length=20), nullable=False),
        sa.Column("post_code", sa.String(length=10), nullable=False),
        sa.Column("base_address", sa.String(length=255), nullable=False),
        sa.Column("detail_address", sa.String(length=255), nullable=True),
        sa.Column("is_default", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_addresses_user_id"), "addresses", ["user_id"], unique=False)
    op.drop_column("users", "address")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("address", sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f("ix_addresses_user_id"), table_name="addresses")
    op.drop_table("addresses")
    # ### end Alembic commands ###
